[package]
name = "rachat"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
color-eyre = "0.6.3"
directories = "6.0.0"
eyre = "0.6.12"
tokio = { version = "1.44.1", features = ["fs"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
