[package]
name = "rachat-qt"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0.144"
cxx-qt = "0.7.1"
cxx-qt-lib = { version = "0.7.1", features = ["qt_gui", "qt_qml"] }

[build-dependencies]
cxx-qt-build = "0.7.1"
