name: Security audit
on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - '**/deny.toml'
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - '**/deny.toml'
  workflow_dispatch: {}
  schedule:
    - cron: "16 19 * * *"
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: EmbarkStudios/cargo-deny-action@34899fc7ba81ca6268d5947a7a16b4649013fea1 # v2
        with:
          command: check